apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: backend-sdk-api
  template:
    metadata:
      labels:
        name: backend-sdk-api
    spec:
      containers:
        - ports:
            - containerPort: 8081
              name: container-port
          name: backend-sdk-api
          resources:
            limits:
              cpu: 750m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          image: backend-sdk-api:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: config
          livenessProbe:
            httpGet:
              path: /ping
              port: container-port
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /ping
              port: container-port
              scheme: HTTP
      restartPolicy: Always
  strategy:
    type: RollingUpdate
